# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.AddField(
            model_name='item',
            name='picture_url',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
